# Generated by Django 4.2.3 on 2023-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.BooleanField(default=True, verbose_name='created'),
        ),
    ]
